package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzmo<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzly<R> zzagT;
  
  public zzmo(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzly)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    this.zzagT = ((zzly)paramPendingResult);
  }
  
  public R await()
  {
    return this.zzagT.await();
  }
  
  public R await(long paramLong, TimeUnit paramTimeUnit)
  {
    return this.zzagT.await(paramLong, paramTimeUnit);
  }
  
  public void cancel()
  {
    this.zzagT.cancel();
  }
  
  public R get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public boolean isCanceled()
  {
    return this.zzagT.isCanceled();
  }
  
  public boolean isDone()
  {
    return this.zzagT.isReady();
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    this.zzagT.setResultCallback(paramResultCallback);
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    this.zzagT.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    this.zzagT.zza(paramzza);
  }
  
  public Integer zzoL()
  {
    return this.zzagT.zzoL();
  }
}


/* Location:              /Users/subdiox/Downloads/dex2jar-2.0/net.wargaming.wot.blitz-dex2jar.jar!/com/google/android/gms/internal/zzmo.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */